#spring.application.name=Movie Review
#server.port=8089
server:
  port: 8089

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: Movie Review

#    DB config
  datasource:
    url: jdbc:h2:./db/test;AUTO_SERVER=TRUE
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.h2.Driver

  liquibase:
    change-log: classpath:/db/changelog/master.yaml
  jpa:
    hibernate:
      ddl-auto: validate

  mvc:
    static-path-pattern: /static/**
    log-request-details: true
  freemarker:
    expose-session-attributes: true
  #    Email
  mail:
    host: smtp.gmail.com
    username: ${EMAIL_SERVER_USERNAME}
    password: ${EMAIL_SERVER_PASSWORD}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # OAuth2.0
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH_CLIENT_ID}
            client-secret: ${OAUTH_CLIENT_SECRET}
            scope:
              - email
              - profile

#  Logging
# ??????? ??????????? (TRACE, DEBUG, INFO, WARN, ERROR)
logging:
  level:
    root: info
    org:
      springframework:
        security: debug
  # ?????? ?????? ?????
  #  pattern:
  #    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
  # ????? ????? ? ????
  file:
    path: log

token:
  signing:
    key: ${JWT_SECRET}

